### ISSUE TITLE
JumpTester too strong

### ISSUE THREAD

**Issue by L-EARN** [L-EARN/NoCheatZ-4#1]
Anti BunnyHop script detects as cheating the consecutive jumps made without any script.

The detection must be more accurate, additionaly it is not a bad idea to make convars for testing what are the best settings to use.

**Comment by Sandman007** [comment]
Is there a way to remove the Anti-BunnyHop part of your cheat detector until you fix this issue? I have an Arena Server and people are constantly bunnyhopping on my server to either gain ground quickly over there opponent or simply for fun after they get kills. I dont want ppl getting banned or kicked for no reason. Maybe I should just hold off until this issue is resolved?

**Comment by L-EARN** [comment]
Players don't get tested for bunnyhopping when the round is ended.

However, if this is special bunnyhop server with a server-sided bunnyhop script or where you allow bunnyhopping, you can disable the system by putting `ncz JumpTester disable` in your server.cfg (Require changelevel) or add JumpTester to the disabled systems list in config.ini (In your game part - Require server restart)

For instance : 

```
[CSTRIKE]
...
f_smoke_time_to_bang=0.75
f_inner_smoke_radius_sqr=5200.0
f_smoke_radius=110.0
disable_systems=JumpTester;AnotherTester;AndAnotherElse
```
