### ISSUE TITLE
[CSS] Couldn't open demo file

### ISSUE THREAD

**Issue by Nerus87** [L-EARN/NoCheatZ-4#104]
Occurred error after join:
> [NoCheatZ v4-beta-r3-patch1] 7.130498 Starting to record the game in NoCheatZ-autorecords/de_dust2-10-17-16_20-01-25.dem
> CDemoFile::Open: couldn't open file NoCheatZ-autorecords/de_dust2-10-17-16_20-01-25.dem for writing.
> StartRecording: couldn't open demo file NoCheatZ-autorecords/de_dust2-10-17-16_20-01-25.dem.

Catalog is set to 777.

Log:
> 10/17/16 20:03:46 [ Server Tick #300] PLAYING ON A NEW MAP : de_dust2
> 10/17/16 20:03:54 [ Server Tick #2635] Player connect : Nerus [[U:1:40175759] - 95.175.16.200:59885]
> 10/17/16 20:03:55 [ Server Tick #2955] TV not detected. Reloading the map ...
> 10/17/16 20:03:56 [ Server Tick #300] PLAYING ON A NEW MAP : de_dust2
> 10/17/16 20:04:03 [ Server Tick #2403] Starting to record the game in NoCheatZ-autorecords/de_dust2-10-17-16_20-04-03.dem

In some case I've got crash.

**Comment by blackhawk74** [comment]
Crash might reference #100

**Comment by L-EARN** [comment]
Make sure the NoCheatZ-autorecords directory already exists. It's placed like the cfg directory but the name is NoCheatZ-autorecords.

And make sure the game is able to record the game by itself ( but first you must disable the autotvrecord system ).

Also you better chown it to your srcds user instead of doing chmod 777, even if this is not sensible files, this is just common security practice.

In any case I will provide another patch soon that will also show the error code, and maybe creating dir automatically ...

Thanks.

**Comment by tooshkan4uk** [comment]
Hello, L-EARN. I have problem with record demo too. I did as you wrote above and that didnt help

**Comment by Nerus87** [comment]
@L-EARN 
Will be nice if there will be an option to store demos remotely on ftp/sftp even in could :)
