### ISSUE TITLE
Feature Request: The ability to display messages about the detection only to admins

### ISSUE THREAD

**Issue by T1MOXA** [L-EARN/NoCheatZ-4#136]
Is it possible to make it only for admins if the server has sourcemod installed ?

**Comment by L-EARN** [comment]
Hi,

I will see if I can simply integrate this without the need of sourcemod.

However I try as much as possible to remove the concept of admins in this plugin, because one day or another someone will ask for immunity ... and this would be against the spirit of the project.

**Comment by L-EARN** [comment]
https://github.com/L-EARN/NoCheatZ-4/releases/tag/v4.0.0-r7

**Comment by T1MOXA** [comment]
Not quite what I need.
Is it possible to define the admin not from config, and from sourcemod API ?

I have a lot of servers and a lot of admins.
And they change frequently...

The config is not the most convenient solution.
Or alternatively make the api for sourcemod.
So I can interact with the anti-cheat from plugins.

**Comment by L-EARN** [comment]
If I use the sm_chat command, it will automatically chat only to admins, am I correct ?

**Comment by T1MOXA** [comment]
Yes

**Comment by T1MOXA** [comment]
Can I build solution for Linux on my computer under Win 10 ?

**Comment by L-EARN** [comment]
You can use cygwin I guess.
Or CMake but the current CMake script of the plugin is broken.

**Comment by T1MOXA** [comment]
```
checking whether we are cross compiling... configure: error: in `/mnt/c/cygwin/home/T1MOXA/NoCheatZ-4/server-plugin/SourceSdk/Interfaces/Protobuf/protobuf-2.5.0':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
Building protobuf 2.5.0
make[2]: Entering directory '/mnt/c/cygwin/home/T1MOXA/NoCheatZ-4/server-plugin/SourceSdk/Interfaces/Protobuf/protobuf-2.5.0'
make[2]: *** No targets specified and no makefile found.  Stop.
make[2]: Leaving directory '/mnt/c/cygwin/home/T1MOXA/NoCheatZ-4/server-plugin/SourceSdk/Interfaces/Protobuf/protobuf-2.5.0'
Makefile:183: recipe for target 'prepare-build' failed
make[1]: *** [prepare-build] Error 2
make[1]: Leaving directory '/mnt/c/cygwin/home/T1MOXA/NoCheatZ-4/server-plugin'
Makefile:147: recipe for target 'release' failed
make: *** [release] Error 2
```

How to fix this ?

**Comment by L-EARN** [comment]
I guess you did not installed the submodule.
https://github.com/L-EARN/SourceSdk-ServerPlugin/tree/d051b3cba786759d31f9f2d37befd6014eaecf11
Everything inside this repository goes into server-plugin/SourceSdk

The highest version of gcc you can use for this project is 4.8, because it gives use the most advanced C++11 tools with the most compatible version of glibc we can use with servers. Using a higher gcc version will make the plugin fail to load.

You need to install g++-4.8 and build using `make release CXX=g++-4.8` command.

After that it should be ok.

**Comment by T1MOXA** [comment]
I have already installed 
https://github.com/L-EARN/SourceSdk-ServerPlugin
and use "release CXX=g++-4.8 to compile" to compile

**Comment by T1MOXA** [comment]
I have noticed many warnings of the type "src/Makefile.am:116: warning: source file 'google/protobuf/compiler/***' is in a subdirectory,
src/Makefile.am:116: but option 'subdir-objects' is disabled"

**Comment by L-EARN** [comment]
Oh yeah I'm sorry.
The error is right in front of my eyes : **configure: error: cannot run C compiled programs.**

I did a quick google search for this problem with cygwin, someone had this issue because of his antivirus.

Anyway the config.log should have something more intesresting to tell. It should be somewhere in server-plugin/SourceSdk/Interfaces/Protobuf/protobuf-2.5.0

For the other errors you see, it's normal.

**Comment by T1MOXA** [comment]
config.log - https://kopy.io/qt5qK#MnKIDJkUEQOC6Z
I don't use cygwin, i use Linux Bash Shell on Windows 10
but before that I tried cygwin (It is for this I have a directory /mnt/c/cygwin)

**Comment by T1MOXA** [comment]
Well, I'll wait.
Thank you :)

**Comment by T1MOXA** [comment]
Maybe I should create a new issue ?

**Comment by L-EARN** [comment]
Yes. :)

**Comment by T1MOXA** [comment]
2 more problems.
1) How to make messages through sm_chat ?
I have a message come in chat to all players
2) And as for messages (in chat), how can i use Unicode ?

**Comment by L-EARN** [comment]
There is no unicode support yet.

An the allowchat command is broken.

**Comment by T1MOXA** [comment]
![image](https://user-images.githubusercontent.com/19938629/28252648-ac89a0ea-6a9f-11e7-8e14-820644a5c7e4.png)

**Comment by T1MOXA** [comment]
It seems that this is a bug of the plugin base chat
