### ISSUE TITLE
[Feature] Autorecord on detection

### ISSUE THREAD

**Issue by Nerus87** [L-EARN/NoCheatZ-4#152]
### The name of the game your server is running on and the version of the game.
Counter-Strike: Source

### Are you using a listen server or a dedicated server?
SRCDS
### Expected behavior?
Start recording player on detection of **hack use** and **save recorded** files to local directory ".../cstrike/NoCheatZ-autorecords" or on to the **remote** dir, with **specific name** e.g. "date_map_steamid".

### Current behavior? (You can link a demo/video and logfiles. Don't forget to strip personal and sensitive informations before.)
Recording whole match.

Regards, Nerus.

**Comment by L-EARN** [comment]
Hi,

If I start the record on detection and stop it when the player is gone, you'll be very disappointed by the results since some testers insta-ban or kick ... your demos will not even contain half a second of gameplay.

Things that is possible to do : 
* Rename recorded demos containing detections with CHEAT-INSIDE-restoffilename for instance.
* Setup a ftp client in the plugin to send demos on a remote server 
* Make a logfile with the same name as the demo containing all detections inside the demo.
* Archive/compress them.
* Delete demos without detection (Not a smart idea because the plugin don't detect everything ... if you need to review a wallhack case but the demo is gone ...)

**Comment by Nerus87** [comment]
About recording 
for me will be fine because I don't care if cheater was fully recorded or not on insta ban, will be nice if we will have a chance to select what we need.
