### ISSUE TITLE
Server startup crash

### ISSUE THREAD

**Issue by SM91337** [L-EARN/NoCheatZ-4#177]
### The name of the game your server is running on and the version of the game.
CSGO

### The version of the plugin release (R) (Otherwise, link to commit/pull request/fork). If using a custom build, please list your compiler version, your server and builder OS versions.
v4-r17

### Are you using other mods (list please) ?
Metamod
NoGlstBan
Sourcemod
PTAH
Messagebot
SendProxy
SMRcon
Socket
SteamWorks

### Are you using a listen server or a dedicated server ?
Dedicated

### Is the server localhost, LAN or remote ? Using Steam ? (A connect-link to a test-server is allowed)
Remote

### Expected behavior ?
Server to start without crash.

### Current behavior ? (You can link a demo/video and logfiles. Don't forget to strip personnal and sensitive informations before.)
Server tries to start then it crashes instantly, Appears to be related to PTAH (Confirmed server starts with above listed modules excluding PTAH)
https://puu.sh/wRnXw/04064cf90d.gif

### Steps to reproduce the problem ?
Install plugin with above listed plugins and start the server.

Crash Dump: https://transfer.sh/j4voS/Dump.zip
Stack trace: https://crash.limetech.org/mcecr3sefz5a

Thanks.

**Comment by L-EARN** [comment]
This error only targets Debug version of the build.

What is happening : 

NoCheatZ hooked SourceHook::AddHook.
PTaH calls SourceHook::AddHook to hook ServerConsolePrint
NoCheatZ calls ServerConsolePrint inside his own version of SourceHook::AddHook
We are now in the PTaH's version of ServerConsolePrint, who is not yet aware of what is the real address of the real ServerConsolePrint, because the hook is not yet complete. So it calls a null pointer = crash.

End of the story.

**Comment by L-EARN** [comment]
This fix introduced a timeout.
It's not a real crash but a timeout that's why you didn't got a stacktrace when you told me about it.

I will fix this soon.

ref @Weeeishy
