### ISSUE TITLE
Server performance severely cripped then eventually crashes

### ISSUE THREAD

**Issue by SM91337** [L-EARN/NoCheatZ-4#25]
**Game:** CSGO
It would appear a function is being spammed for some reason.

**Console:**
http://puu.sh/pjghU/40311d2e1e.png

**Code:**
http://puu.sh/pjglQ/1b03f74403.png

**Minidump:**
http://puu.sh/pjgt6/c93c7050de.zip

**Comment by L-EARN** [comment]
It's normal.

The purpose of EntityProps is to put in cache the offset we need, otherwise we would walk the entire SendProps of the server to found one offset 33 times a seconds for each player, for each offset we need ... hint : the sendprops table for CSGO feels like this 

You print the !FindInCache where it actually found the offset in cache.
DebugMessage + format is really more expensive than entityprops when the offset is in cache.

You better have to use performance tools of visual studio to see what function is more expensive.

**Comment by L-EARN** [comment]
Is it better now ?

**Comment by SM91337** [comment]
Hi, I have added you on steam to speak further about the issue, but with my servers its usually a problem because we get a lot of players and they hate it when we restart the servers, One thing I noticed was its not possible to late load / unload without causing server crash, that would be a nice feature because if it started causing lag then I could just unload it without restarting all the servers again.

I really want to do a lot of testing with this cheat and provide as much support as I possibly can because cheating is a big problem for our servers, but unfortunately I have no C++ knowledge to help development anymore (as much as I would like to) although finding bugs and testing it with a lot of players is something I am willing to do as long as I don't have to restart the server each time.

Thanks!
