### ISSUE TITLE
Cannot find root CONFIG -> Bad support of line endings

### ISSUE THREAD

**Issue by TR1D** [L-EARN/NoCheatZ-4#74]
Debian

Console:
```
Game engine asking for ISERVERPLUGINCALLBACKS003
CNoCheatZPlugin interface created with CSGO callbacks ...
[NoCheatZ v4-beta-r2-debug]  5.35e-07 Loading ...
Detected game CSGO
[NoCheatZ v4-beta-r2-debug] ERROR : ConfigManager::GetIniAttributeValue : Cannot find root CONFIG
[NoCheatZ v4-beta-r2-debug] ERROR : ConfigManager::GetIniAttributeValue : Cannot find attribute CONFIG -> config_version
[NoCheatZ v4-beta-r2-debug] ERROR : ConfigManager::LoadConfig failed
Failed to load plugin "addons/NoCheatZ/nocheatzX"
```
Logs:
```
07/24/2016 12:22:03 AM [ Server Tick #0] ERROR : ConfigManager::GetIniAttributeValue : Cannot find root CONFIG
07/24/2016 12:22:03 AM [ Server Tick #0] ERROR : ConfigManager::GetIniAttributeValue : Cannot find attribute CONFIG -> config_version
07/24/2016 12:22:03 AM [ Server Tick #0] ERROR : ConfigManager::LoadConfig failed
```

**Comment by TR1D** [comment]
Already fixed, https://github.com/atom/line-ending-selector
config.ini & LF :)

```
Game engine asking for ISERVERPLUGINCALLBACKS003
CNoCheatZPlugin interface created with CSGO callbacks ...
[NoCheatZ v4-beta-r2-debug]  7.6e-07 Loading ...
Detected game CSGO
[NoCheatZ v4-beta-r2-debug]  0.029341 ConfigManager : Disabled system validationtester
[NoCheatZ v4-beta-r2-debug]  0.0295522 ConfigManager : Disabled system radarhackblocker
[NoCheatZ v4-beta-r2-debug]  0.0296485 ConfigManager : Disabled system badusercmdblocker
[NoCheatZ v4-beta-r2-debug] 0.0305672 : Starting AutoTVRecord
[NoCheatZ v4-beta-r2-debug]  0.0308902 DEBUG : VirtualTableHook : function 0xF619B100 at 0xF640A424 replaced by 0xED4D463C.
[NoCheatZ v4-beta-r2-debug] 0.0310517 : Starting SpamConnectTester
[NoCheatZ v4-beta-r2-debug]  0.0314631 Loaded
```

**Comment by L-EARN** [comment]
Hi,

Thanks for posting this.

This issue was marked unconfirmed simply because I was not able to reproduce the error.
I will need additionnal informations and even the most dumb things will help me.

Here we go.

Can you provide the detailed steps to reproduce this error ?

Especially those questions may help me : 
* Which version of debian to use
* Which build of NoCheatZ to download (.zip, .tar.gz ?)
* What is the current text encoding of your system ?
* What is the text encoding of the config file you got when decompressed ?
* What is the filesystem of your disk ?

Other check : 
* Is the config.ini file present, not empty, readable and understandable in the addons/NoCheatZ directory ?

Additionally : 
* Are you able to compile the project yourself ?
* Are you able to use GDB to step-debug the code in https://github.com/L-EARN/NoCheatZ-4/blob/master/server-plugin/Code/Systems/ConfigManager.cpp#L20 ?

Thanks for your help.

**Comment by L-EARN** [comment]
Ok thanks.
I did not though about line endings.

I will try to provide support in code for that.

**Comment by L-EARN** [comment]
Builds have been fixed.
