### ISSUE TITLE
version `GLIBCXX_3.4.20' not found

### ISSUE THREAD

**Issue by musosoft** [L-EARN/NoCheatZ-4#89]
Hi,

After compiling and first try, NoCheatZ is throwing following error. What can be the cause?
```
failed to dlopen /hlserver/27657/cstrike/addons/NoCheatZ/nocheatzX.so error=bin/libstdc++.so.6: 
version `GLIBCXX_3.4.20' not found (required by /hlserver/27657/cstrike/addons/NoCheatZ/nocheatzX.so)
```

**Comment by L-EARN** [comment]
This is because the machine executing the server is running an older version of GCC than the machine that compiled the plugin.

The -static-libgcc option in the makefile is here to solve this problem, however some versions of GCC don't take care of it.

Do you the same problem using this ? https://github.com/L-EARN/NoCheatZ-4/releases/tag/v4-beta-r2

**Comment by musosoft** [comment]
4-beta-r2 compiled by you resolved the issue.

Thank you!

**Comment by L-EARN** [comment]
The beta R2 is older than the latest commit.
https://github.com/L-EARN/NoCheatZ-4/compare/v4-beta-r2...master

It will be better if you can compile your own version of the plugin.

**Comment by L-EARN** [comment]
Ok so I came accross the same issue when compiling on a remote debian jessie computer.

Because steam gaes ships with their own version of libstdc++ library, we must use an older version of the compiler.
Debian Jessie ships with g++-4.9.2 and this is higher than the games binary can support.

Compiling using g++-4.8 just works good. All I had to do was to install the g++-4.8 package along with g++-4.8-multilib and fix the makefile.

I will update the makefiles to make the protobuf take account of the custom CXX version because as of right now it is now.

Readme will also be updated.

Thanks.

**Comment by L-EARN** [comment]
This is fixed in https://github.com/L-EARN/NoCheatZ-4/commit/3794966103816590c84f3161206a7efff30f4aa8 .

Here is how you can compile the project now, after you COMPLETLY reset the project : 

Firstly install g++-4.8. There is high chances this package still is in your archives.
`sudo apt-get install g++-4.8 g++-4.8-multilib`

Don't worry, this will not replace the current version of g++ installed in your system.

Next, you can make as usual you just need to specify CXX : 
`make release CXX=g++-4.8`

If you have more questions feel free to comment.

Thanks.
